---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/digit554/public_html/
    - cd repositories/storejv  # Cambia esto a la ruta real de tu repositorio
    - /usr/bin/git pull origin main
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chown -R digit554:digit554 $DEPLOYPATH
