---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/digit554/public_html/
    - /usr/bin/git clone --depth=1 --branch=main https://github.com/tu-usuario/storejv.git /tmp/storejv
    - /bin/cp -R /tmp/storejv/* $DEPLOYPATH
    - /bin/rm -rf /tmp/storejv
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chown -R digit554:digit554 $DEPLOYPATH
