---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/digit554/public_html/
    - cd /home4/digit554/repositories/storejv  # Ruta completa a la subcarpeta storejv en tu cuenta de cPanel
    - /usr/bin/git pull origin main
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chown -R digit554:digit554 $DEPLOYPATH
