<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWHHZEux\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWHHZEux/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerWHHZEux.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerWHHZEux\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerWHHZEux\appAppKernelProdContainer([
    'container.build_hash' => 'WHHZEux',
    'container.build_id' => '97bceb6a',
    'container.build_time' => 1692161602,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWHHZEux');
